# Generated by Django 4.0 on 2022-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_text', models.CharField(max_length=255)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
