name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Run linter
        run: pflake8 turbo
      - name: Run formatter
        run: black --config=pyproject.toml -S --check .
      - name: Run unit tests
        run: pytest tests
